#!/usr/bin/env python

#############################
### AMAZE MODEL SELECTION ###
#############################

__author__ = "Michael Zevin <michael.j.zevin@gmail.com>"
__contributors__ = [
    "Storm Colloms <>",
    "Chris Pankow <>",
    "April Cheng <>"
]

# --- Import packages --- #
import sys
import argparse
import h5py
import warnings
import multiprocessing
from copy import deepcopy
import pdb

import numpy as np
import pandas as pd
import scipy.stats

from populations import models, observations
from sample import sample
import utils.helper_functions as helper_functions


def amaze(ini_file):
    # --- Read in the parsed ini file
    settings = helper_functions.ParseIniFile(ini_file)

    # --- Error check the ini file
    helper_functions.ErrorCheckIni(settings)

    # --- Set random seed
    if settings['random-seed']:
        np.random.seed(settings['random-seed'])

    # --- Set verbosity
    verbose = settings['verbose']

    # --- Load in population models into dictionary structure: models[channel] 
    #     for flows and models[channel][model] for KDEs
    if verbose:
        print("\nReading models, applying transformations, and initializing density estimates for astrophysical populations...\n")
    model_names, pop_models = models.get_models(\
                file_path = settings['path-to-populations'], \
                channel_dict = settings['channels-dict'], \
                param_dict = settings['event-parameter-dict'], \
                hyperparam_dict = settings['population-parameter-dict'], \
                use_flows = settings['use-flows'], \
                flow_path=settings['flow-model-path'], \
                pdet_key=settings['pdet-key'], \
                spinmag=settings['spin-mag-distribution'], \
                max_samps=settings['kde-max-samples'], \
                kde_bandwidth=settings['kde-bandwidth'])

    #grab model hyperparameters from model input file
    model_names.sort()
    hyperparams = sorted(list(set([x.split('/', 1)[1] for x in model_names])))
    Nhyper = np.max([len(x.split('/')) for x in hyperparams])

    # sort channels in alphabetical order
    channels = sorted(list(pop_models.keys()))

    # create dict for the hyperparameters at each level
    hyperparam_dict  = {}
    hyperidx=0
    while hyperidx < Nhyper:
        hyperidx_with_Nhyper = np.argwhere(np.asarray([len(x.split('/')) for x in hyperparams])>hyperidx).flatten()
        hyperparams_at_level = sorted(set([x.split('/')[hyperidx] for x in np.asarray(hyperparams)[hyperidx_with_Nhyper]]))
        hyperparam_dict[hyperidx] = hyperparams_at_level
        hyperidx += 1

    if verbose:
        print("")
        print("Formation channels: [" + ", ".join(channels)+"]")
        print("Astrophysical models: [" + ", ".join(model_names)+"]")
        print("Parameters for inference: [" + ", ".join(settings['population-parameter-dict'])+"]")
        print("")

    # --- Perform some checks to make sure everything is compatible
    helper_functions.ErrorCheckModels(model_names, channels, \
                    Nhyper, settings['true-model'])

    # --- If model0 specified, store KDE models in `model0` dict and save relative fractions
    if settings['true-model'] is not None:
        if verbose:
            print("Saving relative fractions and storing true model...\n")

        # format true model from config appropriately
        true_model = "/".join(settings['true-model'].values())

        # since channels are sorted alphabetically, branching fractions are defined in the same order
        model0 = {}
        for idx, channel in enumerate(channels):
            channel_mdls = [x for x in model_names if channel+'/' in x]
            for model in channel_mdls:
                smdl = model.split('/',1)[1]
                # print info about model0
                if (smdl in true_model):
                    model0[channel] = \
                    helper_functions.GetFromDict(pop_models, model.split('/'))

        # set branching fractions as attributes in KDEModels
        for channel in channels:
            model0[channel].rel_frac(settings['branching-fractions'][channel])

        # print model0 info
        if verbose:
            print("'{0:s}' set as true model".format(true_model))
            print("  model ranges:")
            for channel, mdl in model0.items():
                print("    {0:s} (beta={1:0.2f})".format(channel, mdl.rel_frac))
                for param in settings['event-parameter-dict'].keys():
                    print("      {0:s}: [{1:0.3f},{2:0.3f}]".format(param,\
                            mdl.sample_range[param][0], mdl.sample_range[param][1]))
            print("")


    # --- Generate observations (shape: [observations, params, samples])
    if verbose:
        print("Generating observations...\n")

    pdb.set_trace()
    # Calls observations.py to generate samples if argument is passed
    # NOTE: model0 denotes the 'true' model data if not using actual observations
    if gwobs:
        model0=None
        observations, obsdata, p_theta, events = observations.generate_observations(params, args.gw_path, \
                                                args.Nsamps, args.uncertainty, args.prior)
        if verbose:
            print("Using the following {0:d} observations for inference:".format(len(events)))
            print(*events)
            print("")

    else:
        if verbose:
            print("Drawing {0:d} observations from model0, assuming that the branching fractions represent the *underlying* distribution, and using the '{1:s}' method for measurement uncertainty...".format(int(args.Nobs), args.uncertainty))
        rand_vars = np.random.random(size=args.Nobs)
        randlow_hold = 0
        for idx, channel in enumerate(model0):
            if args.Nobs_probabilistic==True:
                Nobs_per_channel = len(np.where((rand_vars>=randlow_hold) & \
                        (rand_vars<(randlow_hold+model0[channel].rel_frac)))[0])
                randlow_hold += model0[channel].rel_frac
            elif args.Nobs_probabilistic==False:
                # first check that the branching fractions * Nobs are integers
                if not (args.Nobs*model0[channel].rel_frac).is_integer():
                    warnings.warn("Number of observations is not divisble by detectable branching fractions provided, this may result in drawing a number of samples slighty different than what was specified!\n")
                Nobs_per_channel = int(np.round(args.Nobs * model0[channel].rel_frac))
            # add attribute for number of observations drawn
            model0[channel].Nobs_from_beta(Nobs_per_channel)
            if idx==0:
                observations = model0[channel].generate_observations(Nobs_per_channel, args.uncertainty,\
                    sample_from_kde=args.sample_from_kde, sensitivity=args.sensitivity, \
                    multiproc=args.multiproc, verbose=verbose)
                obsdata = model0[channel].measurement_uncertainty(args.Nsamps, \
                    args.uncertainty, observation_noise=True, verbose=verbose)
            else:
                observations = np.concatenate((observations, \
                    model0[channel].generate_observations(Nobs_per_channel, args.uncertainty, \
                    sample_from_kde=args.sample_from_kde, sensitivity=args.sensitivity, \
                    multiproc=args.multiproc, verbose=verbose)))
                obsdata = np.concatenate((obsdata, \
                    model0[channel].measurement_uncertainty(args.Nsamps, \
                    args.uncertainty, observation_noise=True, verbose=verbose)))
        # assume equal prior weight for each posterior sample
        p_theta = np.ones((obsdata.shape[0],obsdata.shape[1]))

    # plot for paper (uncomment if generating)
    #print("\nPlotting marginalized KDE models...")
    #from plot import plot_for_paper
    #observations, obsdata, p_theta, events = gw_obs.generate_observations(params, args.gw_path, args.Nsamps, 'delta')
    #fixed_vals = ['alpha10']
    #plot_for_paper.plot_1D_kdemodels(model_names, kde_models_detectable, params, observations, obsdata, events, model0, name=args.name, fixed_vals=fixed_vals, plot_obs=True, plot_obs_samples=False)
    #exit()

    # Plot the KDEs and observations
    if use_flows==False:
        if make_plots==True:
            if verbose==True:
                print("\nPlotting marginalized KDE models...")
            if len(args.model0.split('/'))>1:
                fixed_vals = [args.model0.split('/')[-1]]
            else:
                fixed_vals = ['alpha10']
            msplot.plot_1D_kdemodels(model_names, kde_models_detectable, params, observations, obsdata, \
                model0, name=args.name, fixed_vals=fixed_vals, plot_obs=True, plot_obs_samples=False)
            if verbose:
                print("")

    # --- Prepare population models
    # If using Flows, train or load a previously trained model for each formation channel
    # If using KDEs, freeze sample evaluations in each model. 
    # This is time consuming, but only needs to be done once for each KDE model, 
    # so we don't need to recompute p_model(data) over and over again when the 
    # observation values aren't going to change.

    if use_flows==True:
        if verbose:
            print('Training/Loading flows')
        for i, channel in enumerate(channels):
            if args.train_flows == True:
                if use_wandb == True:
                    #initialise weights and biases for flow network optimisation
                    pop_models[channel].wandb_init(int(args.epochs[i]))
                else:
                    pop_models[channel].train(int(args.no_trans[i]), int(args.spline_bins[i]), int(args.no_neurons[i]), lr[i], \
                        int(args.epochs[i]), args.batch_no, args.flow_model_filename, device=args.device)
            else:
                pop_models[channel].load_model(args.flow_model_filename, device=args.device)
    else:
        if verbose:
            print("Freezing sample evaluations in their respective models...")
        for model in model_names:
            if verbose:
                print("  {0:s}".format(model))
            #freezing the sample evals means using the call function, this is where the prior on the posterior samples is set in
            getFromDict(pop_models, model.split('/')).freeze(obsdata, smallest_N, data_pdf=p_theta, multiproc=args.multiproc)
        if verbose:
            print("Done freezing KDE evaluations of observations!\n")

    # ---  Copy kde_models so that they all have the same levels of hyperparameters
    all_models_at_deepest = all([len(x.split('/')[1:])==Nhyper for x in model_names])
    while all_models_at_deepest==False:
        # loop until all models have the same length
        for model in model_names:
            # See number of hyperparameters in model, subtract one for channel
            Nhyper_in_model = len(model.split('/'))-1
            if use_flows==False:
                kde_hold = getFromDict(pop_models, model.split('/'))
            # loop until this model has all the hyperparam levels as well
            while Nhyper_in_model < Nhyper:
                if use_flows==False:
                    # remove kde model from old level
                    setInDict(pop_models, model.split('/'), {})
                model_names.remove(model)
                for new_hyperparam in hyperparam_dict[Nhyper_in_model]:
                    if use_flows==False:
                        # copy the same kde model for the higher hyperparam level
                        new_kde = deepcopy(kde_hold)
                        new_level = model.split('/') + [new_hyperparam]
                        setInDict(pop_models, new_level, new_kde)
                    # add new model name
                    model_names.append(model+'/'+new_hyperparam)
                Nhyper_in_model += 1
            model_names.sort()
        # see if all models are at deepest level else repeat
        all_models_at_deepest = all([len(x.split('/')[1:])==Nhyper for x in model_names])

    if args.random_seed:
        np.random.seed(args.random_seed)

    # --- Do the sampling!
    #Here we pass different args is we are doing discrete or continuous sampling of the population model parameters
    if continuous_sample==False:
        hyperparam_bounds = [[0, len(hyperparam_dict[i])] for i in range(Nhyper)]
        sampler = sample.Sampler(model_names, hyperparam_bounds=hyperparam_bounds, likelihood='emcee_lnlike_disc')
    else:
        sampler = sample.Sampler(model_names)
    sampler.sample(pop_models, obsdata, use_flows, smallest_N, continuous_sample, prior_pdf=p_theta, verbose=verbose)
    samples = sampler.samples
    raw_samples = samples.copy()
    lnprb = sampler.lnprb
    submodels_dict = sampler.submodels_dict

    # take the floor of the hyperparameters to get the model indices for discrete sampling
    if continuous_sample==False:
        for hyper_idx in list(submodels_dict.keys()):
            samples[:,:,hyper_idx] = np.floor(samples[:,:,hyper_idx]).astype(int)


    # Reshape to have all steps from all walkers in a single dimension
    original_shape = samples.shape
    samples = samples.reshape((samples.shape[0] * samples.shape[1], samples.shape[2]))
    raw_samples = raw_samples.reshape((raw_samples.shape[0] * raw_samples.shape[1], raw_samples.shape[2]))
    lnprb = lnprb.reshape((lnprb.shape[0] * lnprb.shape[1]))

    # Get samples for both *detectable* branching fractions and *underlying* branching fractions -- for KDEs only
    #requires addition to do this for flows
    if use_flows==False:
        if verbose:
            print("Converting underlying betas from sampler to detectable betas...\n")
        detectable_samples = samples.copy()
        smdls = list(set([x.split('/',1)[1] for x in model_names]))
        # get the conversion factors between the detectable and underlying distributions
        for smdl in sorted(smdls):
            detectable_convfacs = []
            for channel in channels:
                detectable_convfacs.append(getFromDict(kde_models, [channel]+smdl.split('/')).alpha)
            detectable_convfacs = np.asarray(detectable_convfacs)
            # loop over hyperparams to get samples in this submodel
            hyperparams = smdl.split('/')
            for idx, param in enumerate(hyperparams):
                hyper_idx = list(submodels_dict[idx].keys())[list(submodels_dict[idx].values()).index(param)]
                if idx==0:
                    matching_idxs = np.where(samples[:,idx] == hyper_idx)[0]
                    matching_samps = samples[matching_idxs]
                else:
                    matching_idxs = matching_idxs[np.where(matching_samps[:,idx] == hyper_idx)[0]]
                    matching_samps = samples[matching_idxs]
            # if no samples are in this model, continue
            if len(matching_idxs)==0:
                continue
            # convert hyperparams of these samples accordingly to get the underlying betas
            converted_betas = detectable_samples[matching_idxs,len(hyperparams):] * detectable_convfacs
            converted_betas /= converted_betas.sum(axis=1, keepdims=True)
            detectable_samples[matching_idxs,len(hyperparams):] = converted_betas

            # save converted relative fractions to model0
            if smdl==args.model0:
                converted_rel_fracs = betas * detectable_convfacs
                converted_rel_fracs /= np.sum(converted_rel_fracs)
                for cidx, channel in enumerate(channels):
                    model0[channel].rel_frac_detectable(converted_rel_fracs[cidx])

    # --- Print summary info about the sampling
    if verbose:
        print("Sample breakdown:")
        recovered_vals = {}
        smdls = list(set([x.split('/',1)[1] for x in model_names]))
        for smdl in sorted(smdls):
            recovered_vals[smdl] = {}
            hyperparams = smdl.split('/')
            # loop over hyperparams to get matching samples
            for idx, param in enumerate(hyperparams):
                hyper_idx = list(submodels_dict[idx].keys())[list(submodels_dict[idx].values()).index(param)]
                if idx==0:
                    matching_samps = samples[samples[:,idx] == hyper_idx]
                    #matching_samps_detectable = detectable_samples[detectable_samples[:,idx] == hyper_idx]
                else:
                    matching_samps = matching_samps[matching_samps[:,idx] == hyper_idx]
                    #matching_samps_detectable = matching_samps_detectable[matching_samps_detectable[:,idx] == hyper_idx]
            # get counts in this model
            counts = matching_samps.shape[0]
            recovered_vals[smdl]['counts'] = counts
            # get betas for this model from each channel
            recovered_vals[smdl]['betas'] = {}
            recovered_vals[smdl]['betas_detectable'] = {}
            for cidx, channel in enumerate(channels):
                # append beta values for this model
                if counts > 0:
                    beta = matching_samps[:,Nhyper+cidx]
                    beta = round(np.mean(beta), 3)
                    #beta_detectable = matching_samps_detectable[:,Nhyper+cidx]
                    #beta_detectable = round(np.mean(beta_detectable), 3)
                else:
                    beta = np.nan
                    #beta_detectable = np.nan
                recovered_vals[smdl]['betas'][channel] = beta
                #recovered_vals[smdl]['betas_detectable'][channel] = beta_detectable

        # print everything
        for smdl in sorted(smdls):
            sample_counts = recovered_vals[smdl]['counts']
            sample_betas = recovered_vals[smdl]['betas']
            sample_betas_detectable = recovered_vals[smdl]['betas_detectable']
            print("  Model {0:s}".format(smdl))
            print("     {0:d} samples".format(sample_counts))
            print("     betas={0}".format(list(sample_betas.items())))
            print("     detectable betas={0}".format(list(sample_betas_detectable.items())))
        print("")


    # Plot samples and histograms of betas per model
    if make_plots==True:
        if verbose:
            print("Plotting samples...\n")
        for hyper_idx in list(submodels_dict.keys()):
            # Need samples back in their original shape (separated by chains)
            msplot.plot_samples(samples.reshape(original_shape), submodels_dict, model_names, channels, model0, name=args.name, hyper_idx=hyper_idx, detectable_beta=False)
            #msplot.plot_samples(detectable_samples.reshape(original_shape), submodels_dict, model_names, channels, model0, name=args.name, hyper_idx=hyper_idx, detectable_beta=True)


    # --- Save samples

    if args.save_samples:
        if args.name:
            fname = "output_" + args.name + ".hdf5"
        else:
            fname = "output.hdf5"

        if verbose:
            print("Saving information to '{0:s}'...\n".format(fname))

        hfile = h5py.File(fname, "w")
        bsgrp = hfile.create_group("model_selection")

        # add model0 attribute
        if args.model0=='gwobs':
            info = np.append([str(args.model0)], [*events])
        else:
            info = np.append([str(args.model0)], \
                [*[key+': '+str(model0[key].rel_frac) for key in model0.keys()]])
        info = [x.encode('utf-8') for x in info]
        bsgrp.attrs["model0_params"] = info

        # add argument attribute
        arguments = []
        for key, val in vars(args).items():
            arguments.append('{}: {}'.format(key,val))
        bsgrp.attrs["args"] = arguments

        # add submodels_dict attribute
        for hyper_idx in submodels_dict.keys():
            conversion = []
            for key, val in submodels_dict[hyper_idx].items():
                conversion.append(str(key)+': '+str(val))
            bsgrp.attrs["p"+str(hyper_idx)+'_dict'] = conversion
        hfile.close()

        # save observations as dataframe
        df = pd.DataFrame()
        saved_obs_idxs = np.repeat(np.arange(obsdata.shape[0]), obsdata.shape[1])
        saved_obs = np.reshape(obsdata, (-1,len(params)))
        df = pd.DataFrame(saved_obs, columns=params, index=saved_obs_idxs)
        df.to_hdf(fname, key='model_selection/obsdata')

        # save samples as dataframe
        columns = []
        convert_dict = {}
        for hyper_idx in submodels_dict.keys():
            columns.append('p'+str(hyper_idx))
            # save column names to convert model indices to ints
            convert_dict['p'+str(hyper_idx)] = float
        for channel in channels:
            columns.append('beta_'+channel)
        df = pd.DataFrame(samples, columns=columns).astype(convert_dict)
        df.to_hdf(fname, key='model_selection/samples')
        df = pd.DataFrame(raw_samples, columns=columns).astype(convert_dict)
        df.to_hdf(fname, key='model_selection/raw_samples')

        # save detectable samples as dataframe
        columns = []
        convert_dict = {}
        for hyper_idx in submodels_dict.keys():
            columns.append('p'+str(hyper_idx))
            # save column names to convert model indices to ints
            convert_dict['p'+str(hyper_idx)] = float
        for channel in channels:
            columns.append('beta_'+channel)
        #df = pd.DataFrame(detectable_samples, columns=columns).astype(convert_dict)
        df.to_hdf(fname, key='model_selection/detectable_samples')

        # save sample probabilities as dataframe
        df = pd.DataFrame(lnprb, columns=['lnprb'])
        df.to_hdf(fname, key='model_selection/lnprb')


    print_file.close()

# Run main AMAZE function
if __name__ == "__main__":
    amaze(sys.argv[1])