; AMAZE ini file


[MainSettings]
; Path to where the population models are living. Models should be stored
; in hdf5 format, with the channel as the base group, and model parameters
; as subgroups (e.g., 'CE/chi01/alpha0.5').
path-to-populations = /data/wiay/2297403c/models_reduced.hdf5

; Stem for all output files. If missing of None, will not include an
; extra file stem.
output-name = None

; Sets the 'true' model from which mock observations are drawn. Needs to have
; the same number of entries as the number of keys in the 'population-parameters'
; argument. If None or missing, will assume that you are inferring the true
; parameters using observations.
true-model = None

; Dict that specifies which event-level parameters to use in the inference.
; Keys should match the names of the series in the population model data,
; 'limits' specify the bounds to be used for each parameter which is
; necessary to properly rescale the multi-dimensional density estimates
; to a unit cube, and 'fullname' is used for plotting purposes.
event-parameter-dict = {
    'mchirp' : {'limits':(0,100), 'fullname':'Chirp Mass [$M_\\odot$]'},
    'q' : {'limits':(0,1), 'fullname':'Mass Ratio'},
    'chieff' : {'limits':(-1,1), 'fullname':'Effective Inspiral Spin'},
    'z' : {'limits':(0,2), 'fullname':'Redshift'},
    }

; Dict that specifies the population-level parameters used in the inference.
; The keys in the 'values' sub-dictionary should match the keys in the h5 file
; for each population variation. The items in the 'values' dictionary map the
; names of each sub-population to the value of the hyperparameter.
population-parameter-dict = {
    'chib' : {'values':{'chi00':0.0, 'chi01':0.1, 'chi02':0.2, 'chi05':0.5},
        'fullname':'$\\chi_\\mathrm{birth}$',
        'transform':'linear'},
    'alphaCE' : {'values':{'alpha02':0.2, 'alpha05':0.5, 'alpha10':1.0, 'alpha20':2.0, 'alpha50':5.0},
        'fullname':'$\\alpha_\\mathrm{CE}$',
        'transform':'log'}
    }

; Dict that specifies which astrophysical channels are being considered in
; the inference. Keys of this dictionary should match the keys in the h5
; population file. 'parameters' specifies which population hyperparameters
; are varied for each population model.
channels-dict = {
    'CE':  {'parameters':['chib','alphaCE'], 'fullname':'Common Envelope'},
    'CHE': {'parameters':['chib'], 'fullname':'Chemically Homogeneous Evolution'},
    'GC':  {'parameters':['chib'], 'fullname':'Globular Clusters'},
    'NSC': {'parameters':['chib'], 'fullname':'Nuclear Star Clusters'},
    'SMT': {'parameters':['chib'], 'fullname':'Stable Mass Transfer'}
    }

; Boolean argument to determine whether to use normalising flows to estimate
; hyperlikelihoods in inference. Otherwise, KDEs will be used.
use-flows = True

; Boolean argument to determine whether hyperparameter inference should be
; done on a continuous range (True) or discretely at the locations of the
; training models (False). Continuous inference can only be performed if
; use-flows is True.
continuous-sampling = True


[RealObservations]
; Path where observational samples live. Must be set if not using mock
; observations in the analysis.
event-samples-path = /data/wiay/2297403c/amaze_model_select/Nflows_AMAZE_paper/inputs/GWTC-3/events

; Key for the series that contains prior evaluations for the event-level
; posterior samples, which needs to be divided out when performing
; hierarchical inference. If None, will assume that the priors are
; already divided out for the samples in 'event-samples-path' (i.e., this
; file contains samples from the likelihood.
event-level-prior = p_theta_jcb


[MockObservations]
; Dict that specifies underlying branching fractions of each channel for
; the injected model when using mock observations. Values must sum to unity.
branching-fractions = {
    'CE'  : 0.2,
    'CHE' : 0.2,
    'GC'  : 0.2,
    'NSC' : 0.2,
    'SMT' : 0.2
    }

; Specifies how to mock up measurement uncertainties for mock observations.
; Available options are:
; 'delta': a single sample taken at the true value
; 'snr': assumes Gaussian-distributed likelihood with a SNR-dependent sigma
; 'events': assumes Gaussian with sigma taken from average spread from observed events
uncertainty = posteriors

; Number of mock observations to be taken from the mixture model.
n-observations = 100

; Name of desired sensitivity to be used when drawing mock observations.
; Should be consistent with the string following the 'pdet' columns in the
; population dataframes, which specified the detection probability for each
; sample. These weights are used when drawing observed samples from the underlying
; population models.
sensitivity = None

; Boolean to determine whether to draw mock observations probabilistically based on
; using random number generator and the supplied branching fractions. This will lead
; to the branching fractions not being exactly equal to the supplied values. If set
; to False, code will do the best rounding it can based on the input branching
; fractions if not perfectly divisible.
probabilistic-draws = False


[Flows]
; File name used for saving/loading flow models. If this model already exists,
; the already-trained model can be loaded in if 'train-flows' = False.
flow-model-path = /data/wiay/2297403c/amaze_model_select/Nflows_AMAZE_paper/inputs/flow_models/mixed_models

; Boolean that determines whether to train new flows (True) or to load in
; pre-existing flow model (False).
train-flows = False

; Dictionary that specifies parameters that are used in training the flows for.
; each formation channel. Defaults are:
; 'learning-rate': 0.0001 for NSC, 0.001 for the rest of the channels
; 'epochs': 1000 for CE, 500 for the rest of the channels
; 'spline-bins': 4 for all channels
; 'N-transformations': 6 for all channels
; 'N-neurons': 128 for all channels
flow-settings = {
    'CE'  : {'learning-rate' : 0.001,
            'epochs' : 1000,
            'spline-bins' : 5,
            'N-transformations' : 6,
            'N-neurons' : 128
        },
    'CHE' : {'learning-rate' : 0.001,
            'epochs' : 500,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128
        },
    'GC'  : {'learning-rate' : 0.001,
            'epochs' : 500,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128
        },
    'NSC' : {'learning-rate' : 0.0001,
            'epochs' : 500,
            'spline-bins' : 5,
            'N-transformations' : 6,
            'N-neurons' : 128
        },
    'SMT' : {'learning-rate' : 0.001,
            'epochs' : 500,
            'spline-bins' : 4,
            'N-transformations' : 6,
            'N-neurons' : 128
        }
    }

; Number of batches used to train flow models.
N-batches = 10

; Device to run the inference on when using flows. Default is 'cpu'. When
; using GPU, should write 'cuda:X' where X is the slot of the GPU
device = cuda:0

; Boolean that determines whether of not to use weights and biases to run a
; sweep over optimizing parameters of the normailizing flows.
use-wandb = False


[ExtraOptions]
; Boolean to determine verbosity
verbose = True

; Boolean to determine whether to make diagnostic plots during the inference.
make-plots = False

; Sets random seed
random-seed = 11

; Determine number of processesors used for multithreading the freezing of samples
; in the KDE models and drawing samples from the underlying distributions in mock
; observations.
multiproc-KDE = 1

; Number of samples to be drawn from the event posterior distributions. Increasing
; this will increase computation time since these posteriors all need to be frozen
; in the population models.
N-samples = 100

; If not None, will be used at the N in the regularization during inference
regularization-N = None

[DeletableSettings]
# argp.add_argument("--normalize-kde", action="store_true", help="If True, will normalize KDE to unit cube. Default is False.")
; should always do this
# argp.add_argument("--sample-from-kde", action="store_true", help="If True, events are drawn probabalistically from the detection-weighted KDE. Otherwise, samples drawn from the actual population models, weighted by pdet. These *should* result in similar results (modulo sampling uncertainty). Default is False.")
; we can get rid of detection-weighted KDEs entirely
# argp.add_argument("--testCEmodel", action="store_true", help="If true removes the chi_b=0.1, alphaCE=1.0 training samples during the flow training to test interpolation.")
; shouldn't hardcord this
# argp.add_argument("--save-samples", action="store_true", help="Save all the samples rather than just the summary statistics. Default is False.")
; always save samples
# argp.add_argument("--spinmag", type=str, help="Define the spin magnitude distribution you wish to use. Required for using spin parameters in populations where the spin magnitude is not specified. Default is None.")
; spins should be in pop models if we want to infer them
